version: '3.8'

services:

  database:
    container_name: database
    ports:
      - 5434:5432
    image: postgres:14.7
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      # DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./database_volume:/data
    networks:
      transcendance:

  back:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    container_name: back
    ports:
      - '3001:3001'
      - '5555:5555'
    depends_on:
      - database
    volumes:
      - ./backend:/app
    networks:
      - transcendance

  front:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    container_name: front
    ports:
      - '3000:3000'
    depends_on:
      - back
    volumes:
      - ./frontend:/app
    networks:
      - transcendance

networks:
  transcendance:
